<script setup lang="ts">
import { ref, computed } from "vue";

const chips = ref([
  "All",
  "Query Builder",
  "Plans",
  "User Accounts",
  "Databases",
]);

const accordionData = ref([
  {
    heading: "What is a SQL Builder Web App?",
    desc: "A SQL Builder Web App is a tool designed to help users construct SQL queries visually, without needing to write the SQL code manually. It provides a user-friendly interface where users can drag-and-drop tables, select columns, apply filters, and define joins to generate SQL queries effortlessly.",
  },
  {
    heading: "Who can benefit from using the SQL Builder Web App?",
    desc: "Anyone who needs to interact with databases but may not be proficient in writing SQL code can benefit from using the SQL Builder Web App. This includes business analysts, data scientists, software developers, and even students learning about databases.",
  },
  {
    heading: "How does the SQL Builder Web App work?",
    desc: "The SQL Builder Web App typically consists of a graphical user interface (GUI) where users can visually construct their queries. Users can select the tables they want to query from, choose the columns they need, apply filters to narrow down the results, and specify join conditions to link multiple tables together. The app then generates the corresponding SQL code based on the user's selections.",
  },
  {
    heading: "Is the SQL code generated by the app customizable?",
    desc: "Yes, most SQL Builder Web Apps allow users to customize the generated SQL code. Users can review the generated code, make modifications if necessary, and execute the query against their database.",
  },
  {
    heading: "What databases are supported by the SQL Builder Web App?",
    desc: "The databases supported by a SQL Builder Web App depend on the app itself and its compatibility with various database management systems (DBMS). Commonly supported databases include MySQL, PostgreSQL, SQL Server, Oracle, SQLite, and others.",
  },
  {
    heading:
      "Can I save and reuse queries created with the SQL Builder Web App?",
    desc: "Yes, many SQL Builder Web Apps offer functionality to save queries for future use. Users can save their queries with meaningful names and organize them into folders or categories for easy retrieval.",
  },
  {
    heading: "Is the SQL Builder Web App suitable for complex queries?",
    desc: "While SQL Builder Web Apps are excellent for constructing simple to moderately complex queries, extremely complex queries may require manual SQL coding expertise. However, advanced features in some SQL Builder apps may support more complex query construction.",
  },
  {
    heading: "Is the SQL Builder Web App secure?",
    desc: "Security features may vary among SQL Builder Web Apps. It's essential to choose a reputable app that prioritizes security and offers features like encryption, role-based access control, and secure connections to databases to ensure the safety of your data.",
  },
  {
    heading:
      "Can I integrate the SQL Builder Web App with other tools or applications?",
    desc: "Many SQL Builder Web Apps offer APIs or integrations with other tools and applications. This allows users to seamlessly incorporate query building functionality into their existing workflows, such as business intelligence platforms, data visualization tools, or custom applications.",
  },
  {
    heading: "Is there a learning curve to using the SQL Builder Web App?",
    desc: "The learning curve for using a SQL Builder Web App varies depending on the user's familiarity with databases and query concepts. However, most apps are designed to be intuitive and user-friendly, with helpful documentation and tutorials available to assist users in getting started.",
  },
]);
</script>
<template>
  <div class="p-7">
    <div class="pb-4 font-bold text-xl">Frequently Asked Questions</div>
    <div class="pb-4">
      <Chip :label="chip" class="mr-2 text-sm font-medium" v-for="(chip, index) in chips" :key="index" />
    </div>
    <div class="card">
      <Accordion :activeIndex="0">
        <AccordionTab :header="data.heading" v-for="(data, index) in accordionData" :key="index">
          <p class="m-0">
            {{ data.desc }}
          </p>
        </AccordionTab>
      </Accordion>
    </div>
  </div>
</template>
